apiVersion: v1
kind: Pod
metadata:
  name: k8s-practice
  label: 
    - name: pod-creator
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    ports:
    - containerPort: 80
  
   