apiVersion: v1
kind: Pod
metadata: 
  name: multipod
  namespace: namespace
  labels:
    name: dev
spec: 
  containers:
  - name: nginx
    image: nginx:alpine
  - name: almalinux
    image: almalinux:latest
    command: ["sleep","1000"]