apiVersion: v1
kind: Pod
metadata:
  name: annotations
  namespace: namespace
  labels:
    name: dev
  annotations: 
    imagerepository: https://hub.docker.com/
    kubernetesdocument: https://kubernetes.io/
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80