apiVersion: v1
kind: Pod
metadata:
  name: configpod
  namespace: namespace
  labels:
    name: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:latest
    envForm:
      - configMapRef:
          name: configmap 