apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer
  selector: 
    names: roboshop
    env: dev
    language: yaml
    cpurpose: loadbalancer
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: servicepod
  labels:
    names: roboshop
    env: dev
    language: yaml
    purpose: loadbalancer
spec:
  containers:
  - name: nginx
    image: nginx:latest
    